// Arrange weather text lookup (from Weatherunlocked API)
let weather_obj_arranged = {}

const weather_obj = [
    {
      "code": 0,
      "en": "Sunny skies/Clear skies",
      "da": "Solrigt/Skyfrit",
      "fr": "Ensoleillé/Dégagé",
      "it": "Sereno/Soleggiato",
      "de": "Sonnig",
      "nl": "Zonnig/Helder",
      "es": "Soleado/Despejado",
      "no": "Klar himmel/Sol",
      "sv": "Klart/Soligt",
      "tr": "Açik gökyüzü/Günesli gökyüzü",
      "bg": "Ясно небе/Слънчево време",
      "cs": "Jasno/Slunecno",
      "hu": "Derült égbolt/Napfényes égbolt",
      "pl": "Bezchmurne niebo/Slonecznie",
      "rm": "Cer senin/Cer înseninat",
      "ru": "Ясно/Солнце",
      "sk": "Jasno/Slnecno",
      "jp": "快晴"
    },
    {
      "code": 1,
      "en": "Partly cloudy skies",
      "da": "Halvskyet",
      "fr": "Altern.nuages/soleil",
      "it": "Parzialmente nuvoloso",
      "de": "Teilw. Bewölkt",
      "nl": "Gedeeltelijk bewolkt",
      "es": "Parcialmente nuboso",
      "no": "Delvis skyet",
      "sv": "Delvis molnigt",
      "tr": "Parçali bulutlu gökyüzü",
      "bg": "Разкъсана облачност",
      "cs": "Polojasno",
      "hu": "Enyhén felhos égbolt",
      "pl": "Zachmurzenie czesciowe",
      "rm": "Cer partial senin",
      "ru": "Переменная облачность",
      "sk": "Polooblacno",
      "jp": "所によりくもり"
    },
    {
      "code": 2,
      "en": "Cloudy skies",
      "da": "Skyet",
      "fr": "Nuageux",
      "it": "Nuvoloso",
      "de": "Bewölkt",
      "nl": "Bewolkt",
      "es": "Nuboso",
      "no": "Skyet",
      "sv": "Molnigt",
      "tr": "Bulutlu gökyüzü",
      "bg": "Облачно време",
      "cs": "Oblacno",
      "hu": "Felhos égbolt",
      "pl": "Zachmurzenie",
      "rm": "Cer acoperit cu nori",
      "ru": "Облачно",
      "sk": "Oblacno",
      "jp": "くもり"
    },
    {
      "code": 3,
      "en": "Overcast skies",
      "da": "Overskyet",
      "fr": "Couvert",
      "it": "Coperto",
      "de": "Bedeckt",
      "nl": "Zwaar bewolkt",
      "es": "Cubierto",
      "no": "Overskyet",
      "sv": "Mulet",
      "tr": "Kapali gökyüzü",
      "bg": "Ниска облачност",
      "cs": "Zataženo",
      "hu": "Borús égbolt",
      "pl": "Zachmurzone niebo",
      "rm": "Cer înnorat",
      "ru": "Пасмурно",
      "sk": "Zamracené",
      "jp": "どんよりしたくもり"
    },
    {
      "code": 10,
      "en": "Mist",
      "da": "Let tågedis",
      "fr": "Brumeux",
      "it": "Foschia",
      "de": "Dunst",
      "nl": "Nevel",
      "es": "Neblina",
      "no": "Dis",
      "sv": "Dimma",
      "tr": "Pus",
      "bg": "Намалена видимост",
      "cs": "Kourmo",
      "hu": "Ködfátyol",
      "pl": "Mgla",
      "rm": "Ceata",
      "ru": "Туман",
      "sk": "Hmla",
      "jp": "霧"
    },
    {
      "code": 21,
      "en": "Patchy rain possible",
      "da": "Stedvis let regn",
      "fr": "Quelques pluies",
      "it": "Possibilità di piogge sparse",
      "de": "Gelegentlich Regen",
      "nl": "Af en toe regen",
      "es": "Lluvia ligera aislada o llovizna",
      "no": "Mulighet for spredte regnbyger",
      "sv": "Risk för spridda regnskurar",
      "tr": "Yer yer yagmur olasiligi",
      "bg": "Вероятност за превалявания",
      "cs": "Ojedinele déšt",
      "hu": "Elszórtan eso várható",
      "pl": "Przelotne deszcze",
      "rm": "Pe alocuri, posibile precipitatii sub forma de ploaie",
      "ru": "Местами возможен дождь",
      "sk": "Možný lokálny dážd",
      "jp": "所により雨"
    },
    {
      "code": 22,
      "en": "Patchy snow possible",
      "da": "Lokale lette sludbyger",
      "fr": "Averses de grésil",
      "it": "Possibilità di nevicate sparse",
      "de": "Leichte Graupelsch.",
      "nl": "Natte sneeuwbuien",
      "es": "Chubascos ligeros de aguanieve aislados",
      "no": "Mulighet for spredte snøbyger",
      "sv": "Risk för spridda snöbyar",
      "tr": "Yer yer kar olasiligi",
      "bg": "Вероятност за превалявания от сняг",
      "cs": "Ojedinele snežení",
      "hu": "Elszórtan hó várható",
      "pl": "Przelotne opady sniegu",
      "rm": "Pe alocuri, posibile precipitatii sub forma de ninsoare",
      "ru": "Местами возможен снег",
      "sk": "Možné lokálne sneženie",
      "jp": "所により雪"
    },
    {
      "code": 23,
      "en": "Patchy sleet possible",
      "da": "Stedvis let slud",
      "fr": "Grésil occasionnel",
      "it": "Possibilità di nevischio sparso",
      "de": "Geleg. Schneeregen",
      "nl": "Soms natte sneeuw",
      "es": "Ligera aguanieve aislada",
      "no": "Mulighet for spredt sludd",
      "sv": "Risk för spridda skurar av snöblandat regn",
      "tr": "Yer yer sulu kar olasiligi",
      "bg": "Вероятност за превалявания от мокър сняг",
      "cs": "Ojedinele déšt se snehem",
      "hu": "Elszórtan hódara eshet",
      "pl": "Przelotny snieg z deszczem",
      "rm": "Pe alocuri, posibile precipitatii sub forma de lapovita",
      "ru": "Местами возможен мокрый снег",
      "sk": "Možný lokálny dážd so snehom",
      "jp": "所によりみぞれ"
    },
    {
      "code": 24,
      "en": "Patchy freezing drizzle possible",
      "da": "Let isslag",
      "fr": "Brume givrante",
      "it": "Possibilità di pioviggine ghiacciata sparsa",
      "de": "Leichter Schneeregen",
      "nl": "Lichte natte sneeuw",
      "es": "Llovizna helada",
      "no": "Mulighet for spredt yr som fryser på bakken",
      "sv": "Risk för spridda skurar av underkylt duggregn",
      "tr": "Yer yer donan çisenti olasiligi",
      "bg": "Вероятност за преръмявания",
      "cs": "Ojedinele mrznoucí mrholení",
      "hu": "Elszórtan dérszitálás várható",
      "pl": "Przelotna marznaca mzawka",
      "rm": "Pe alocuri, posibile precipitatii sub forma de chiciura",
      "ru": "Местами возможен дождь и гололед",
      "sk": "Možné lokálne mrznúce mrholenie",
      "jp": "所により着氷性の霧雨"
    },
    {
      "code": 29,
      "en": "Thundery outbreaks possible",
      "da": "Delvist overskyet med regn og risiko for torden",
      "fr": "Pluies orageuses",
      "it": "Possibili rovesci temporaleschi",
      "de": "Regen/Gewitter",
      "nl": "Regen/donder",
      "es": "Parcialmente nuboso con lluvias y riesgo de tormentas",
      "no": "Mulighet for torden",
      "sv": "Risk för åskskurar",
      "tr": "Gök gürültülü firtina olasiligi",
      "bg": "Вероятност за гръмотевици",
      "cs": "Výskyt bourek",
      "hu": "Hirtelen kitöro viharok várhatók",
      "pl": "Mozliwe burze",
      "rm": "Posibile fulgere",
      "ru": "Возможны кратковременные грозы",
      "sk": "Možné náhle búrky",
      "jp": "雷の可能性"
    },
    {
      "code": 38,
      "en": "Blowing snow",
      "da": "Sne",
      "fr": "Neige modérée",
      "it": "Raffiche di neve",
      "de": "Schneefall",
      "nl": "Matige sneeuw",
      "es": "Nieve moderada",
      "no": "Snøstorm",
      "sv": "Drivande snö",
      "tr": "Savrulan kar",
      "bg": "Снежна виелица",
      "cs": "Snehová vánice",
      "hu": "Hófúvás",
      "pl": "Opady sniegu",
      "rm": "Zapada viscolita",
      "ru": "Ветер со снегом",
      "sk": "Vietor so snehom",
      "jp": "吹雪"
    },
    {
      "code": 39,
      "en": "Blizzard",
      "da": "Snestorm",
      "fr": "Blizzard",
      "it": "Bufera di neve",
      "de": "Schneestürme",
      "nl": "Sneeuwstormen",
      "es": "Ventiscas",
      "no": "Kraftig snøstorm",
      "sv": "Snöstorm",
      "tr": "Tipi",
      "bg": "Гръмотевична буря",
      "cs": "Blizard",
      "hu": "Hóvihar",
      "pl": "Zamiec",
      "rm": "Viscol",
      "ru": "Метель",
      "sk": "Snehová búrka",
      "jp": "暴風雨"
    },
    {
      "code": 45,
      "en": "Fog",
      "da": "Tåge",
      "fr": "Brouillard",
      "it": "Nebbia",
      "de": "Nebel",
      "nl": "Mist",
      "es": "Niebla",
      "no": "Tåke",
      "sv": "Dimma",
      "tr": "Sis",
      "bg": "Мъгла",
      "cs": "Mlha",
      "hu": "Köd",
      "pl": "Mgla",
      "rm": "Ceata",
      "ru": "Сильный туман",
      "sk": "Hmla",
      "jp": "霧"
    },
    {
      "code": 49,
      "en": "Freezing fog",
      "da": "Stedvis rimtåge",
      "fr": "Brouillard givrant",
      "it": "Nebbia ghiacciata",
      "de": "Gefrierende Nässe",
      "nl": "Rijp",
      "es": "Niebla helada discontinua",
      "no": "Iståke",
      "sv": "Isdimma",
      "tr": "Donan sis",
      "bg": "Мъгла със скреж",
      "cs": "Mrznoucí mlha",
      "hu": "Jeges köd",
      "pl": "Marznaca mgla",
      "rm": "Ceata care îngheata",
      "ru": "Сильный туман и гололед",
      "sk": "Mrznúca hmla",
      "jp": "着氷性の霧"
    },
    {
      "code": 50,
      "en": "Patchy light drizzle",
      "da": "Lokale lette regnbyger",
      "fr": "Averses éparses",
      "it": "Possibilità di pioviggine sparsa",
      "de": "Leichte Regenschauer",
      "nl": "Lichte buien",
      "es": "Chubascos ligeros aislados",
      "no": "Mulighet for spredt lett yr",
      "sv": "Risk för spridda skurar av lätt duggregn",
      "tr": "Yer yer hafif çisenti olasiligi",
      "bg": "Вероятност за слабо ръмене",
      "cs": "Ojedinele slabé mrholení",
      "hu": "Elszórtan szitáló eso várható",
      "pl": "Przelotna, lekka mzawka",
      "rm": "Pe alocuri, posibile precipitatii sub forma de burnita",
      "ru": "Местами возможен моросящий дождь",
      "sk": "Možné slabé lokálne mrholenie",
      "jp": "所々で弱い霧雨"
    },
    {
      "code": 51,
      "en": "Light drizzle",
      "da": "Stedvis let regn",
      "fr": "Quelques pluies",
      "it": "Pioviggine",
      "de": "Gelegentlich Regen",
      "nl": "Af en toe regen",
      "es": "Lluvia ligera aislada o llovizna",
      "no": "Lett yr",
      "sv": "Lätt duggregn",
      "tr": "Hafif çisenti",
      "bg": "Слабо ръмене",
      "cs": "Slabé mrholení",
      "hu": "Szitáló eso",
      "pl": "Lekka mzawka",
      "rm": "Burnita",
      "ru": "Моросящий дождь",
      "sk": "Slabé mrholenie",
      "jp": "弱い霧雨"
    },
    {
      "code": 56,
      "en": "Freezing drizzle",
      "da": "Let isslag",
      "fr": "Brume givrante",
      "it": "Pioviggine ghiacciata",
      "de": "Leichter Schneeregen",
      "nl": "Lichte natte sneeuw",
      "es": "Llovizna helada",
      "no": "Yr som fryser på bakken",
      "sv": "Underkylt duggregn",
      "tr": "Donan çisenti",
      "bg": "Ръмене",
      "cs": "Mrznoucí mrholení",
      "hu": "Jeges szitálás",
      "pl": "Marznaca mzawka",
      "rm": "Chiciura",
      "ru": "Дождь и гололед",
      "sk": "Mrznúce mrholenie",
      "jp": "着氷性の霧雨"
    },
    {
      "code": 57,
      "en": "Heavy freezing drizzle",
      "da": "Let isslag",
      "fr": "Brume givrante",
      "it": "Pioggia forte ghiacciata",
      "de": "Leichter Schneeregen",
      "nl": "Lichte natte sneeuw",
      "es": "Llovizna helada",
      "no": "Tett yr som fryser på bakken",
      "sv": "Kraftigt underkylt duggregn",
      "tr": "Yogun donan çisenti",
      "bg": "Силно ръмене",
      "cs": "Silné mrznoucí mrholení",
      "hu": "Jeges, suru eso",
      "pl": "Ciezka marznaca mzawka",
      "rm": "Chiciura densa",
      "ru": "Сильный дождь и гололед",
      "sk": "Silné mrznúce mrholenie",
      "jp": "強い着氷性の霧雨"
    },
    {
      "code": 60,
      "en": "Patchy light rain",
      "da": "Stedvis let regn",
      "fr": "Quelques pluies",
      "it": "Possibilità di piogge deboli sparse",
      "de": "Gelegentlich Regen",
      "nl": "Af en toe regen",
      "es": "Lluvia ligera aislada o llovizna",
      "no": "Mulighet for spredte lette regnbyger",
      "sv": "Risk för spridda skurar av lätt regn",
      "tr": "Yer yer hafif siddette yagmur olasiligi",
      "bg": "Вероятност за слаби превалявания от дъжд",
      "cs": "Ojedinele slabý déšt",
      "hu": "Elszórtan enyhe eso várható",
      "pl": "Przelotne lekkie opady deszczu",
      "rm": "Pe alocuri, posibile precipitatii slabe sub forma de ploaie",
      "ru": "Местами возможен моросящий дождь",
      "sk": "Možný slabý lokálny dážd",
      "jp": "所により弱い雨"
    },
    {
      "code": 61,
      "en": "Light rain",
      "da": "Regn",
      "fr": "Pluie modérée",
      "it": "Pioggia debole",
      "de": "Regen",
      "nl": "Matige regen",
      "es": "Lluvia moderada",
      "no": "Lette regnbyger",
      "sv": "Lätt regn",
      "tr": "Hafif siddette yagmur",
      "bg": "Слаб дъжд",
      "cs": "Slabý déšt",
      "hu": "Enyhe eso",
      "pl": "Lekkie opady deszczu",
      "rm": "Ploi slabe",
      "ru": "Небольшой дождь",
      "sk": "Slabý dážd",
      "jp": "弱い雨"
    },
    {
      "code": 62,
      "en": "Moderate rain at times",
      "da": "Regnbyger",
      "fr": "Averses modérées",
      "it": "Pioggia moderata a tratti",
      "de": "Regenschauer",
      "nl": "Matige buien",
      "es": "Chubascos moderados",
      "no": "Til tider moderate regnbyger",
      "sv": "Tidvis måttligt regn",
      "tr": "Zaman zaman orta siddette yagmur",
      "bg": "Умерен дъжд на места",
      "cs": "Obcasný mírný déšt",
      "hu": "Idonként közepes erosségu eso",
      "pl": "Umiarkowane opady deszczu przez czesc dnia",
      "rm": "Ploi moderate intermitente",
      "ru": "Временами дождь",
      "sk": "Obcas mierny dážd",
      "jp": "時々中程度の雨"
    },
    {
      "code": 63,
      "en": "Moderate rain",
      "da": "Regn",
      "fr": "Pluie modérée",
      "it": "Pioggia moderata",
      "de": "Regen",
      "nl": "Matige regen",
      "es": "Lluvia moderada",
      "no": "Moderate regnbyger",
      "sv": "Måttligt regn",
      "tr": "Orta siddette yagmur",
      "bg": "Умерен дъжд",
      "cs": "Mírný déšt",
      "hu": "Közepes erosségu eso",
      "pl": "Umiarkowane opady deszczu",
      "rm": "Ploi moderate",
      "ru": "Дождь",
      "sk": "Mierny dážd",
      "jp": "中程度の雨"
    },
    {
      "code": 64,
      "en": "Heavy rain at times",
      "da": "Kraftige regnbyger",
      "fr": "Fortes averses",
      "it": "Pioggia forte a tratti",
      "de": "Ergiebige Regensch.",
      "nl": "Zware buien",
      "es": "Fuertes chubascos",
      "no": "Til tider kraftige regnbyger",
      "sv": "Tidvis kraftigt regn",
      "tr": "Zaman zaman siddetli yagmur",
      "bg": "Силен дъжд на места",
      "cs": "Obcasný silný déšt",
      "hu": "Idonként heves eso",
      "pl": "Silne opady deszczu przez czesc dnia",
      "rm": "Ploi torentiale intermitente",
      "ru": "Местами сильный дождь",
      "sk": "Obcas silný dážd",
      "jp": "時々大雨"
    },
    {
      "code": 65,
      "en": "Heavy rain",
      "da": "Kraftigt regnvejr",
      "fr": "Fortes pluies",
      "it": "Pioggia forte",
      "de": "Ergiebiger Regen",
      "nl": "Zware regen",
      "es": "Fuertes lluvias",
      "no": "Kraftige regnbyger",
      "sv": "Kraftigt regn",
      "tr": "Siddetli yagmur",
      "bg": "Силен дъжд",
      "cs": "Silný déšt",
      "hu": "Heves eso",
      "pl": "Silne opady deszczu",
      "rm": "Ploi torentiale",
      "ru": "Сильный дождь",
      "sk": "Silný dážd",
      "jp": "大雨"
    },
    {
      "code": 66,
      "en": "Light freezing rain",
      "da": "Isslag",
      "fr": "Pluie verglaçante",
      "it": "Gelicidio leggero",
      "de": "Schneeregen",
      "nl": "Natte sneeuw",
      "es": "Lluvia helada",
      "no": "Lett regn som fryser",
      "sv": "Lätt underkylt regn",
      "tr": "Hafif siddette donan yagmur",
      "bg": "Слаба суграшица",
      "cs": "Slabý mrznoucí déšt",
      "hu": "Enyhe, jeges eso",
      "pl": "Lekki, marznacy deszcz",
      "rm": "Ploaie slaba care îngheata",
      "ru": "Небольшой дождь и гололед",
      "sk": "Slabý mrznúci dážd",
      "jp": "軽い着氷性の雨"
    },
    {
      "code": 67,
      "en": "Moderate or heavy freezing rain",
      "da": "Isslag",
      "fr": "Pluie verglaçante",
      "it": "Pioggia moderata o gelicidio forte",
      "de": "Schneeregen",
      "nl": "Natte sneeuw",
      "es": "Lluvia helada",
      "no": "Moderat eller kraftig regn som fryser",
      "sv": "Måttligt eller kraftigt underkylt regn",
      "tr": "Orta siddette veya siddetli donan yagmur",
      "bg": "Умерена или силна суграшица",
      "cs": "Mírný nebo silný mrznoucí déšt",
      "hu": "Közepes erosségu vagy heves, jeges eso",
      "pl": "Umiarkowane lub silne opady marznacego deszczu",
      "rm": "Ploi moderate sau puternice care îngheata",
      "ru": "Дождь/ливень и гололед",
      "sk": "Mierny alebo silný mrznúci dážd",
      "jp": "中程度または強い着氷性の雨"
    },
    {
      "code": 68,
      "en": "Light sleet",
      "da": "Slud",
      "fr": "Grêle",
      "it": "Nevischio leggero",
      "de": "Schneeregen",
      "nl": "Matige natte sneeuw",
      "es": "Aguanieve moderada",
      "no": "Lett sludd",
      "sv": "Lätt snöblandat regn",
      "tr": "Hafif siddette sulu kar",
      "bg": "Слаба лапавица",
      "cs": "Slabý déšt se snehem",
      "hu": "Enyhe hódara",
      "pl": "Lekkie opady deszczu ze sniegiem",
      "rm": "Lapovita slaba",
      "ru": "Небольшой мокрый снег",
      "sk": "Dážd so snehom",
      "jp": "弱いみぞれ"
    },
    {
      "code": 69,
      "en": "Moderate or heavy sleet",
      "da": "Kraftig slud",
      "fr": "Forte grêle",
      "it": "Nevischio moderato o pesante",
      "de": "Ergiebiger Schneeregen",
      "nl": "Zware natte sneeuw",
      "es": "Fuerte aguanieve",
      "no": "Moderat eller kraftig sludd",
      "sv": "Måttligt eller kraftigt snöblandat regn",
      "tr": "Orta siddette veya siddetli sulu kar",
      "bg": "Умерена или силна лапавица",
      "cs": "Mírný nebo silný déšt se snehem",
      "hu": "Közepes erosségu vagy heves hódara",
      "pl": "Umiarkowane lub silne opady deszczu ze sniegiem",
      "rm": "Lapovita moderata sau puternica",
      "ru": "Мокрый снег/сильный мокрый снег",
      "sk": "Mierny alebo silný dážd so snehom",
      "jp": "中程度または強いみぞれ"
    },
    {
      "code": 70,
      "en": "Patchy light snow",
      "da": "Stedvis let sne",
      "fr": "Flocons épars",
      "it": "Possibilità di neve a piccole falde sparsa",
      "de": "Geleg. Schneefall",
      "nl": "Af en toe sneeuw",
      "es": "Ligera nieve aislada",
      "no": "Mulighet for spredte lette snøbyger",
      "sv": "Risk för lätta snöbyar",
      "tr": "Yer yer hafif siddette kar olasiligi",
      "bg": "Вероятност за слаб снеговалеж на места",
      "cs": "Ojedinele slabé snežení",
      "hu": "Elszórtan enyhe havazás várható",
      "pl": "Przelotne, lekkie opady sniegu",
      "rm": "Pe alocuri, posibile precipitatii slabe sub forma de zapada",
      "ru": "Местами возможен небольшой снег",
      "sk": "Možné slabé lokálne sneženie",
      "jp": "所により弱い雪"
    },
    {
      "code": 71,
      "en": "Light snow",
      "da": "Stedvis let sne",
      "fr": "Flocons épars",
      "it": "Neve a piccole falde",
      "de": "Geleg. Schneefall",
      "nl": "Af en toe sneeuw",
      "es": "Ligera nieve aislada",
      "no": "Lette snøbyger",
      "sv": "Lätt snöfall",
      "tr": "Hafif siddette kar",
      "bg": "Слаб сняг",
      "cs": "Slabé snežení",
      "hu": "Enyhe havazás",
      "pl": "Lekkie opady sniegu",
      "rm": "Zapada slaba",
      "ru": "Небольшой снег",
      "sk": "Slabé sneženie",
      "jp": "弱い雪"
    },
    {
      "code": 72,
      "en": "Patchy moderate snow",
      "da": "Sne",
      "fr": "Neige modérée",
      "it": "Possibilità di neve moderata sparsa",
      "de": "Schneefall",
      "nl": "Matige sneeuw",
      "es": "Nieve moderada",
      "no": "Mulighet for spredte moderate snøbyger",
      "sv": "Risk för måttliga snöbyar",
      "tr": "Yer yer orta siddette kar olasiligi",
      "bg": "Вероятност за умерен снеговалеж на места",
      "cs": "Ojedinele mírné snežení",
      "hu": "Elszórtan közepes erosségu havazás várható",
      "pl": "Przelotne, umiarkowane opada sniegu",
      "rm": "Pe alocuri, posibile precipitatii moderate sub forma de zapada",
      "ru": "Местами возможен снег",
      "sk": "Možné mierne lokálne sneženie",
      "jp": "所により中程度の雪"
    },
    {
      "code": 73,
      "en": "Moderate snow",
      "da": "Sne",
      "fr": "Neige modérée",
      "it": "Neve moderata",
      "de": "Schneefall",
      "nl": "Matige sneeuw",
      "es": "Nieve moderada",
      "no": "Moderate snøbyger",
      "sv": "Måttligt snöfall",
      "tr": "Orta siddette kar",
      "bg": "Умерен снеговалеж",
      "cs": "Mírné snežení",
      "hu": "Közepes erosségu havazás",
      "pl": "Umiarkowane opady sniegu",
      "rm": "Zapada moderata",
      "ru": "Снег",
      "sk": "Mierne sneženie",
      "jp": "中程度の雪"
    },
    {
      "code": 74,
      "en": "Patchy heavy snow",
      "da": "Kraftige regnbyger",
      "fr": "Fortes ch. de neige",
      "it": "Possibilità di neve a grandi falde sparsa",
      "de": "Ergiebige Schneesch.",
      "nl": "Zware sneeuwbuien",
      "es": "Fuertes chubascos de nieve",
      "no": "Mulighet for spredte kraftige snøbyger",
      "sv": "Risk för spridda kraftiga snöbyar",
      "tr": "Yer yer siddetli kar olasiligi",
      "bg": "Вероятност за силен снеговалеж на места",
      "cs": "Ojedinele silné snežení",
      "hu": "Elszórtan heves havazás várható",
      "pl": "Przelotne, ciezkie opady sniegu",
      "rm": "Posibile precipitatii puternice sub forma de zapada",
      "ru": "Местами возможен сильный снег",
      "sk": "Možné silné lokálne sneženie",
      "jp": "所により大雪"
    },
    {
      "code": 75,
      "en": "Heavy snow",
      "da": "Kraftigt snevejr",
      "fr": "Neige abondante",
      "it": "Neve a grandi falde",
      "de": "Ergiebiger Schneefall",
      "nl": "Zware sneeuw",
      "es": "Fuerte nieve",
      "no": "Kraftige snøbyger",
      "sv": "Kraftigt snöfall",
      "tr": "Siddetli kar",
      "bg": "Силен снеговалеж",
      "cs": "Silné snežení",
      "hu": "Heves havazás",
      "pl": "Silne opady sniegu",
      "rm": "Zapada puternica",
      "ru": "Сильный снег",
      "sk": "Silné sneženie",
      "jp": "大雪"
    },
    {
      "code": 79,
      "en": "Ice pellets",
      "da": "Isslag",
      "fr": "Pluie verglaçante",
      "it": "Grandine",
      "de": "Schneeregen",
      "nl": "Natte sneeuw",
      "es": "Lluvia helada",
      "no": "Hagl",
      "sv": "Hagel",
      "tr": "Buz taneleri",
      "bg": "Градушка",
      "cs": "Zmrzlý déšt",
      "hu": "Jégdara",
      "pl": "Grad",
      "rm": "Granule de gheata",
      "ru": "Ледяной дождь",
      "sk": "Zmrznutý dážd",
      "jp": "凍雨"
    },
    {
      "code": 80,
      "en": "Light rain shower",
      "da": "Lokale lette regnbyger",
      "fr": "Averses éparses",
      "it": "Breve rovescio di pioggia",
      "de": "Leichte Regenschauer",
      "nl": "Lichte buien",
      "es": "Chubascos ligeros aislados",
      "no": "Lett regnbyge",
      "sv": "Lätt regnskur",
      "tr": "Hafif siddette saganak yagmur",
      "bg": "Слаб проливен дъжд",
      "cs": "Slabé deštové prehánky",
      "hu": "Enyhe zivatar",
      "pl": "Lekkie opady deszczu",
      "rm": "Aversa slaba de ploaie",
      "ru": "Кратковременные ливни",
      "sk": "Slabá daždová prehánka",
      "jp": "弱い雨"
    },
    {
      "code": 81,
      "en": "Moderate or heavy rain shower",
      "da": "Regnbyger",
      "fr": "Averses modérées",
      "it": "Rovescio di pioggia moderato o nubifragio",
      "de": "Regenschauer",
      "nl": "Matige buien",
      "es": "Chubascos moderados",
      "no": "Moderat eller kraftig regnbyge",
      "sv": "Måttlig eller kraftig regnskur",
      "tr": "Orta siddette veya siddetli saganak yagmur",
      "bg": "Умерен или силен проливен дъжд",
      "cs": "Mírné nebo silné deštové prehánky",
      "hu": "Közepes erosségu vagy heves zivatar",
      "pl": "Umiarkowane lub silne opady deszczu",
      "rm": "Averse de ploaie moderate sau puternice",
      "ru": "Кратковременные дожди/ливни",
      "sk": "Mierna alebo silná daždová prehánka",
      "jp": "中程度または大雨"
    },
    {
      "code": 82,
      "en": "Torrential rain shower",
      "da": "Kraftigt regnvejr",
      "fr": "Pluies torrentielles",
      "it": "Pioggia torrenziale",
      "de": "Sehr starker Regen",
      "nl": "Zeer zware regen",
      "es": "Muy fuertes lluvias",
      "no": "Svært kraftig regnbyge",
      "sv": "Skyfallsliknande regnskur",
      "tr": "Çok siddetli saganak yagmur",
      "bg": "Пороен дъжд",
      "cs": "Prutrž mracen",
      "hu": "Zuhogó eso",
      "pl": "Ulewne deszcze",
      "rm": "Aversa de ploaie torentiala",
      "ru": "Проливной дождь",
      "sk": "Prehánka s prívalovým daždom",
      "jp": "豪雨"
    },
    {
      "code": 83,
      "en": "Light sleet showers",
      "da": "Sludbyger",
      "fr": "Averses de grêle",
      "it": "Nevischio leggero",
      "de": "Graupelschauer",
      "nl": "Matige natte sneeuwb",
      "es": "Chubascos de aguanieve moderados",
      "no": "Lette sluddbyger",
      "sv": "Lätta skurar av snöblandat regn",
      "tr": "Hafif siddette saganak sulu kar",
      "bg": "Слаба продължителна лапавица",
      "cs": "Slabé prehánky dešte se snehem",
      "hu": "Enyhe daraeso",
      "pl": "Lekkie opady deszczu ze sniegiem",
      "rm": "Averse de lapovita slaba",
      "ru": "Кратковременный мокрый снег",
      "sk": "Slabé prehánky dažda so snehom",
      "jp": "弱いみぞれ"
    },
    {
      "code": 84,
      "en": "Moderate or heavy sleet showers",
      "da": "Sludbyger",
      "fr": "Fortes av. de grêle",
      "it": "Nevischio moderato o pesante",
      "de": "Ergiebige Graupelsch.",
      "nl": "Zware natte sneeuwb",
      "es": "Fuertes chubascos de aguanieve",
      "no": "Moderate eller kraftige sluddbyger",
      "sv": "Måttliga eller kraftiga skurar av snöblandat regn",
      "tr": "Orta siddette veya siddetli saganak sulu kar",
      "bg": "Умерена или силна продължителна лапавица",
      "cs": "Mírné nebo silné prehánky dešte se snehem",
      "hu": "Közepes erosségu vagy heves daraeso",
      "pl": "Umiarkowane lub silne opady deszczu ze sniegiem",
      "rm": "Averse de lapovita moderate sau puternice",
      "ru": "Кратковременный мокрый снег/сильный мокрый снег",
      "sk": "Mierne alebo silné prehánky dažda so snehom",
      "jp": "中程度または強いみぞれ"
    },
    {
      "code": 85,
      "en": "Light snow showers",
      "da": "Lokale lette snebyger",
      "fr": "Ch. de neige éparses",
      "it": "Rovesci nevosi leggeri",
      "de": "Leichte Schneesch.",
      "nl": "Lichte sneeuwbuien",
      "es": "Ligeros chubascos de nieve aislados",
      "no": "Lette snøbyger",
      "sv": "Lätta snöbyar",
      "tr": "Hafif siddette saganak kar",
      "bg": "Слаб продължителен снеговалеж",
      "cs": "Slabé snehové prehánky",
      "hu": "Enyhe hózivatar",
      "pl": "Lekkie opady sniegu",
      "rm": "Averse de zapada slabe",
      "ru": "Небольшой кратковременный снег",
      "sk": "Slabé snehové prehánky",
      "jp": "弱い雪"
    },
    {
      "code": 86,
      "en": "Moderate or heavy snow showers",
      "da": "Regnbyger",
      "fr": "Chutes de neige",
      "it": "Rovesci nevosi moderati o pesanti",
      "de": "Schneeschauer",
      "nl": "Matige sneeuwbuien",
      "es": "Chubascos de nieve moderados",
      "no": "Moderat eller kraftig snøvær",
      "sv": "Måttliga eller kraftiga snöbyar",
      "tr": "Orta siddette veya siddetli saganak kar",
      "bg": "Умерен или силен продължителен снеговалеж",
      "cs": "Mírné nebo silné snehové prehánky",
      "hu": "Közepes erosségu vagy heves hózivatar",
      "pl": "Umiarkowane lub silne opady sniegu",
      "rm": "Averse de zapada moderate sau puternice",
      "ru": "Кратковременный снег/сильный снег",
      "sk": "Mierne alebo silné snehové prehánky",
      "jp": "中程度または大雪"
    },
    {
      "code": 87,
      "en": "Light showers of ice pellets",
      "da": "Isslag",
      "fr": "Pluie verglaçante",
      "it": "Grandinata leggera",
      "de": "Schneeregen",
      "nl": "Natte sneeuw",
      "es": "Lluvia helada",
      "no": "Lette haglbyger",
      "sv": "Lätta hagelskurar",
      "tr": "Hafif siddette saganak buz taneleri",
      "bg": "Слаба продължителна градушка",
      "cs": "Slabé zmrzlé deštové prehánky",
      "hu": "Enyhe jeges daraeso",
      "pl": "Lekkie opady gradu",
      "rm": "Averse de granule de gheata slabe",
      "ru": "Кратковременный небольшой ледяной дождь",
      "sk": "Slabé prehánky zmrznutého dažda",
      "jp": "弱い凍雨"
    },
    {
      "code": 88,
      "en": "Moderate or heavy showers of ice pellets",
      "da": "Isslag",
      "fr": "Pluie verglaçante",
      "it": "Grandinata moderata o intensa",
      "de": "Schneeregen",
      "nl": "Natte sneeuw",
      "es": "Lluvia helada",
      "no": "Moderate eller kraftige haglbyger",
      "sv": "Måttliga eller kraftiga hagelskurar",
      "tr": "Orta siddette veya siddetli saganak buz taneleri",
      "bg": "Умерена или силна продължителна градушка",
      "cs": "Mírné nebo silné zmrzlé deštové prehánky",
      "hu": "Közepes erosségu vagy viharos jeges daraeso",
      "pl": "Umiarkowane lub silne opady gradu",
      "rm": "Averse de granule de gheata moderate sau puternice",
      "ru": "Кратковременные ледяные ливни",
      "sk": "Mierne alebo silné prehánky zmrznutého dažda",
      "jp": "中程度または強い凍雨"
    },
    {
      "code": 91,
      "en": "Patchy light rain with thunder",
      "da": "Delvist overskyet med regn og risiko for torden",
      "fr": "Pluies orageuses",
      "it": "Piogge deboli sparse e tuoni",
      "de": "Regen/Gewitter",
      "nl": "Regen/donder",
      "es": "Parcialmente nuboso con lluvias y riesgo de tormentas",
      "no": "Spredte lette regnbyger med torden",
      "sv": "Spridda skurar av lätt regn med åska",
      "tr": "Yer yer gök gürültülü hafif siddette yagmur",
      "bg": "Слаб дъжд с гръмотевици на места",
      "cs": "Ojedinele slabý déšt s bourkou",
      "hu": "Elszórtan enyhe zivatar villámlással",
      "pl": "Przelotne lekkie opady deszczu z piorunami",
      "rm": "Pe alocuri, ploi slabe cu tunete",
      "ru": "Местами небольшой дождь с грозой",
      "sk": "Slabá lokálna búrka",
      "jp": "所により雷雨"
    },
    {
      "code": 92,
      "en": "Moderate or heavy rain with thunder",
      "da": "Skyet med regn og risiko for torden",
      "fr": "Pluies orageuses",
      "it": "Piogge forti o moderate con tuoni",
      "de": "Regen/Gewitter",
      "nl": "Regen/donder",
      "es": "Nuboso con lluvias y riesgo de tormentas",
      "no": "Moderate eller kraftige regnbyger med torden",
      "sv": "Måttligt eller kraftigt regn med åska",
      "tr": "Gök gürültülü orta siddette veya siddetli yagmur",
      "bg": "Умерен или силен дъжд с гръмотевици на места",
      "cs": "Mírný nebo silný déšt s bourkou",
      "hu": "Közepesen eros vagy heves zivatar villámlással",
      "pl": "Umiarkowane lub silne opady deszczu z piorunami",
      "rm": "Ploaie moderata sau puternica cu tunete",
      "ru": "Дождь/ливень с грозой",
      "sk": "Mierna alebo silná búrka",
      "jp": "中程度または強い雷雨"
    },
    {
      "code": 93,
      "en": "Patchy light snow with thunder",
      "da": "Delvist overskyet med sne eller slud og risiko for torden",
      "fr": "Grêle/neige orageuse",
      "it": "Nevicate leggere e sparse con tuoni",
      "de": "Winterlich/Gewitter",
      "nl": "Winterachtig/donder",
      "es": "Parcialmente nuboso con aguanieve o nieve y riesgo de tormentas",
      "no": "Spredte lette snøbyger med torden",
      "sv": "Spridda lätta snöbyar med åska",
      "tr": "Yer yer gök gürültülü hafif siddette kar",
      "bg": "Слаб сняг с гръмотевици на места",
      "cs": "Ojedinele slabé snežení s bourkou",
      "hu": "Elszórtan enyhe havazás villámlással",
      "pl": "Przelotne lekkie opady sniegu z piorunami",
      "rm": "Pe alocuri, zapada slaba cu tunete",
      "ru": "Местами небольшой снег с грозой",
      "sk": "Slabá lokálna snehová búrka",
      "jp": "所により弱い雷雪"
    },
    {
      "code": 94,
      "en": "Moderate or heavy snow with thunder",
      "da": "Skyet med slud eller sne og risiko for torden",
      "fr": "Grêle/Neige orageuse",
      "it": "Rovesci nevosi moderati o forti con tuoni",
      "de": "Winterlich/Gewitter",
      "nl": "Winterachtig/donder",
      "es": "Nuboso con aguanieve o nieve y riesgo de tormentas",
      "no": "Moderate eller kraftige snøbyger med torden",
      "sv": "Måttliga eller kraftiga snöbyar med åska",
      "tr": "Gök gürültülü orta siddette veya siddetli kar",
      "bg": "Умерен или силен сняг с гръмотевици на места",
      "cs": "Mírné nebo silné snežení s bourkou",
      "hu": "Közepesen eros vagy heves havazás villámlással",
      "pl": "Umiarkowane lub silne opady sniegu z piorunami",
      "rm": "Zapada moderata sau puternica cu tunete",
      "ru": "Снег/сильный снег с грозой",
      "sk": "Mierna alebo silná snehová búrka",
      "jp": "中程度または強い雷雪"
    }
  ]

for(var i  = 0; i < weather_obj.length; i++) {
  let this_wobj = weather_obj[i]
  weather_obj_arranged[this_wobj.code] = this_wobj
}

export default weather_obj_arranged